services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./client/Dockerfile
      target: production
      args:
        REACT_APP_GOOGLE_CLIENT_ID: "632974279988-p8ui6tg3201kgmr6p0q17dtoq1fqt0s1.apps.googleusercontent.com"
    ports:
      - '80:80'
    depends_on:
      - server
      - mongo
    restart: unless-stopped

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      NODE_ENV: production
      MONGO_URL: mongodb://mongo:27017/accountill
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    restart: unless-stopped
  
  mongo:
    image: mongo:6
    container_name: MONGODB
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: {}
